CREATE TABLE Caracteristicas(
    ID INT NOT NULL AUTO_INCREMENT,
    icono VARCHAR(400) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Categorias(
    ID INT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(252) NOT NULL,
    urlImagen VARCHAR(400),
    PRIMARY KEY (id), 
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Productos(
    ID INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    urlImagen VARCHAR(455),
    deporte VARCHAR (255),
    genero VARCHAR(255),
    PRIMARY KEY (id),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ImagenProductos(
    ID INT NOT NULL AUTO_INCREMENT,
    url VARCHAR(455),
    PRIMARY KEY (id),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Asset(
    contenido VARCHAR(255),
    contentType VARCHAR(255),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Users(
    ID INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);