CREATE TABLE Caracteristicas(
    ID INT NOT NULL AUTO_INCREMENT,
    icono VARCHAR(400) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Categorias(
    ID INT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(252) NOT NULL,
    urlImagen VARCHAR(400),
    PRIMARY KEY (id), 
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE productos(
    ID INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    deporte VARCHAR (255),
    genero VARCHAR(255),
    PRIMARY KEY (id),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ImagenProductos(
    ID INT NOT NULL AUTO_INCREMENT,
    url VARCHAR(255),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Asset(
    contenido VARCHAR(255),
    contentType VARCHAR(255),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Usuarios(
    ID INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    nombreDeUsuario VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);